# Project-wide Gradle settings.
# See https://docs.gradle.org/current/userguide/build_environment.html

# Specifies the JVM arguments used for the daemon process.
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8

# Android build features
android.useAndroidX=true

# Kotlin code style
kotlin.code.style=official

# Gradle non-transitive R classes
android.nonTransitiveRClass=true
